// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260916024429_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("AutorLivro", b =>
                {
                    b.Property<int>("AutoresId")
                        .HasColumnType("int");

                    b.Property<int>("LivrosId")
                        .HasColumnType("int");

                    b.HasKey("AutoresId", "LivrosId");

                    b.HasIndex("LivrosId");

                    b.ToTable("AutorLivro");
                });

            modelBuilder.Entity("WebApplication1.Entities.Autor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_aut");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento_aut");

                    b.Property<string>("Nacionalidade")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nacionalidade_aut");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome_aut");

                    b.HasKey("Id");

                    b.ToTable("autores");
                });

            modelBuilder.Entity("WebApplication1.Entities.Emprestimo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_emp");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("DataEfetivaDevolucao")
                        .HasColumnType("date")
                        .HasColumnName("data_efetiva_devolucao_emp");

                    b.Property<DateOnly>("DataEmprestimo")
                        .HasColumnType("date")
                        .HasColumnName("data_emprestimo_emp");

                    b.Property<DateOnly>("DataPrevistaDevolucao")
                        .HasColumnType("date")
                        .HasColumnName("data_prevista_devolucao_emp");

                    b.Property<int>("LivroId")
                        .HasColumnType("int")
                        .HasColumnName("livro_id_emp");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id_emp");

                    b.Property<decimal>("ValorMulta")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("valor_multa_emp");

                    b.HasKey("Id");

                    b.HasIndex("LivroId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("emprestimos");
                });

            modelBuilder.Entity("WebApplication1.Entities.Livro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_liv");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AnoPublicacao")
                        .HasColumnType("int")
                        .HasColumnName("ano_publicacao_liv");

                    b.Property<string>("Editora")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("editora_liv");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("genero_liv");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("isbn_liv");

                    b.Property<int>("QuantidadeDisponivel")
                        .HasColumnType("int")
                        .HasColumnName("quantidade_disponivel_liv");

                    b.Property<int>("QuantidadeTotalExemplares")
                        .HasColumnType("int")
                        .HasColumnName("quantidade_total_liv");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("titulo_liv");

                    b.HasKey("Id");

                    b.ToTable("livros");
                });

            modelBuilder.Entity("WebApplication1.Entities.Penalidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_pen");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataPenalidade")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_pen");

                    b.Property<int>("DiasAtraso")
                        .HasColumnType("int")
                        .HasColumnName("dias_atraso_pen");

                    b.Property<int>("EmprestimoId")
                        .HasColumnType("int")
                        .HasColumnName("emprestimo_id_pen");

                    b.Property<string>("StatusPagamento")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status_pagamento_pen");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id_pen");

                    b.Property<decimal>("ValorMulta")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("valor_multa_pen");

                    b.HasKey("Id");

                    b.HasIndex("EmprestimoId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("penalidades");
                });

            modelBuilder.Entity("WebApplication1.Entities.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_res");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_expiracao_res");

                    b.Property<DateTime>("DataReserva")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("data_reserva_res");

                    b.Property<int>("LivroId")
                        .HasColumnType("int")
                        .HasColumnName("livro_id_res");

                    b.Property<int>("PosicaoFila")
                        .HasColumnType("int")
                        .HasColumnName("posicao_fila_res");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("status_res");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int")
                        .HasColumnName("usuario_id_res");

                    b.HasKey("Id");

                    b.HasIndex("LivroId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("reservas");
                });

            modelBuilder.Entity("WebApplication1.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usu");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("cpf_usu");

                    b.Property<DateOnly>("DataNascimento")
                        .HasColumnType("date")
                        .HasColumnName("data_nascimento_usu");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email_usu");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("endereco_usu");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nome_usu");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("telefone_usu");

                    b.HasKey("Id");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("AutorLivro", b =>
                {
                    b.HasOne("WebApplication1.Entities.Autor", null)
                        .WithMany()
                        .HasForeignKey("AutoresId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Entities.Livro", null)
                        .WithMany()
                        .HasForeignKey("LivrosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WebApplication1.Entities.Emprestimo", b =>
                {
                    b.HasOne("WebApplication1.Entities.Livro", "Livro")
                        .WithMany("Emprestimos")
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WebApplication1.Entities.Penalidade", b =>
                {
                    b.HasOne("WebApplication1.Entities.Emprestimo", "Emprestimo")
                        .WithMany()
                        .HasForeignKey("EmprestimoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Emprestimo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WebApplication1.Entities.Reserva", b =>
                {
                    b.HasOne("WebApplication1.Entities.Livro", "Livro")
                        .WithMany("Reservas")
                        .HasForeignKey("LivroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Livro");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("WebApplication1.Entities.Livro", b =>
                {
                    b.Navigation("Emprestimos");

                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
